services:
  reservations:
    build:
      context: ..
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - ..:/usr/src/app
    env_file:
      -  .env # Adjust this path if your .env file is located somewhere else
  mongo:
    image: mongo